import type { BoatPreset } from "./types.js";

export const BOAT_PRESETS: BoatPreset[] = [
  {
    id: "sailboat",
    name: "Sailboat",
    description: "Small sailboat with triangular sail on calm water",
    tags: ["sail", "yacht", "small", "leisure"],
    category: "boat",
    boatType: "sailboat",
    color: "#4A3A30",
    sailColor: "#F0E8D8",
    scale: 0.06,
    xPosition: 0.5,
    yPosition: 0.55,
    tilt: 0,
  },
  {
    id: "rowboat",
    name: "Rowboat",
    description: "Simple wooden rowboat with bench seat",
    tags: ["row", "small", "wood", "simple"],
    category: "boat",
    boatType: "rowboat",
    color: "#5A4030",
    sailColor: "#8A7060",
    scale: 0.04,
    xPosition: 0.4,
    yPosition: 0.6,
    tilt: 0,
  },
  {
    id: "fishing-boat",
    name: "Fishing Boat",
    description: "Fishing boat with cabin and mast",
    tags: ["fishing", "cabin", "mast", "work"],
    category: "boat",
    boatType: "fishing",
    color: "#3A4A60",
    sailColor: "#E0D8C8",
    scale: 0.07,
    xPosition: 0.6,
    yPosition: 0.55,
    tilt: 0,
  },
  {
    id: "cargo-ship",
    name: "Cargo Ship",
    description: "Large cargo ship with superstructure and funnel",
    tags: ["ship", "cargo", "large", "industrial"],
    category: "boat",
    boatType: "ship",
    color: "#3A3A3A",
    sailColor: "#C0C0C0",
    scale: 0.1,
    xPosition: 0.5,
    yPosition: 0.5,
    tilt: 0,
  },
];
