import type { BridgePreset } from "./types.js";

export const BRIDGE_PRESETS: BridgePreset[] = [
  {
    id: "stone-arch",
    name: "Stone Arch",
    description: "Classic stone arch bridge spanning a river or valley",
    tags: ["stone", "arch", "classic", "river"],
    category: "bridge",
    bridgeStyle: "arch",
    color: "#6A6060",
    deckColor: "#8A7A70",
    span: 0.4,
    xPosition: 0.5,
    yPosition: 0.6,
    archHeight: 0.08,
    railingHeight: 0.02,
  },
  {
    id: "wooden-footbridge",
    name: "Wooden Footbridge",
    description: "Simple wooden footbridge with slight arc and rope railings",
    tags: ["wood", "footbridge", "simple", "rural"],
    category: "bridge",
    bridgeStyle: "footbridge",
    color: "#6A5040",
    deckColor: "#8A7060",
    span: 0.3,
    xPosition: 0.5,
    yPosition: 0.65,
    archHeight: 0.05,
    railingHeight: 0.025,
  },
  {
    id: "suspension-bridge",
    name: "Suspension Bridge",
    description: "Tall suspension bridge with tower pylons and cable stays",
    tags: ["suspension", "cables", "tall", "modern"],
    category: "bridge",
    bridgeStyle: "suspension",
    color: "#505050",
    deckColor: "#707070",
    span: 0.5,
    xPosition: 0.5,
    yPosition: 0.6,
    archHeight: 0.1,
    railingHeight: 0.015,
  },
  {
    id: "flat-crossing",
    name: "Flat Crossing",
    description: "Low flat bridge or causeway crossing with support pillars",
    tags: ["flat", "low", "crossing", "causeway"],
    category: "bridge",
    bridgeStyle: "flat",
    color: "#707060",
    deckColor: "#909080",
    span: 0.35,
    xPosition: 0.5,
    yPosition: 0.65,
    archHeight: 0.05,
    railingHeight: 0.0,
  },
];
