import type { BuildingPreset } from "./types.js";

export const BUILDING_PRESETS: BuildingPreset[] = [
  {
    id: "farmhouse",
    name: "Farmhouse",
    description: "Simple rural farmhouse with pitched roof and small windows",
    tags: ["farm", "rural", "simple", "house"],
    category: "building",
    buildingType: "farmhouse",
    color: "#5A5050",
    roofColor: "#704030",
    scale: 1.0,
    xPosition: 0.5,
    yPosition: 0.6,
    windowCount: 2,
  },
  {
    id: "church-steeple",
    name: "Church Steeple",
    description: "Country church with tall steeple and spire rising above the roofline",
    tags: ["church", "steeple", "spire", "village"],
    category: "building",
    buildingType: "church",
    color: "#E0D8D0",
    roofColor: "#504540",
    scale: 1.2,
    xPosition: 0.5,
    yPosition: 0.6,
    windowCount: 3,
  },
  {
    id: "tower-ruin",
    name: "Tower Ruin",
    description: "Ruined stone tower or castle keep silhouette on a hilltop",
    tags: ["tower", "ruin", "castle", "medieval"],
    category: "building",
    buildingType: "tower",
    color: "#6A6060",
    roofColor: "#6A6060",
    scale: 1.0,
    xPosition: 0.5,
    yPosition: 0.55,
    windowCount: 1,
  },
  {
    id: "village-cluster",
    name: "Village Cluster",
    description: "Small cluster of buildings forming a hamlet or village silhouette",
    tags: ["village", "cluster", "hamlet", "rural"],
    category: "building",
    buildingType: "village",
    color: "#5A5050",
    roofColor: "#704030",
    scale: 0.8,
    xPosition: 0.5,
    yPosition: 0.6,
    windowCount: 1,
  },
  {
    id: "temple",
    name: "Temple",
    description: "Asian-style temple silhouette with broad sweeping roof",
    tags: ["temple", "asian", "roof", "traditional"],
    category: "building",
    buildingType: "farmhouse",
    color: "#4A4040",
    roofColor: "#3A3030",
    scale: 1.3,
    xPosition: 0.5,
    yPosition: 0.55,
    windowCount: 0,
  },
  {
    id: "lighthouse",
    name: "Lighthouse",
    description: "Tall coastal lighthouse tower on a rocky point",
    tags: ["lighthouse", "coastal", "tower", "tall"],
    category: "building",
    buildingType: "tower",
    color: "#E0D8D0",
    roofColor: "#C04030",
    scale: 1.1,
    xPosition: 0.7,
    yPosition: 0.55,
    windowCount: 1,
  },
];
