import type { CelestialPreset } from "./types.js";

export const CELESTIAL_PRESETS: CelestialPreset[] = [
  {
    id: "noon-sun",
    name: "Noon Sun",
    description: "Bright white sun high in the sky with a wide soft glow",
    tags: ["sun", "noon", "bright", "warm"],
    category: "celestial",
    bodyType: "sun",
    elevation: 0.85,
    azimuth: 0.5,
    size: 0.04,
    glowRadius: 0.15,
    glowColor: "#FFFDE0",
    bodyColor: "#FFFFFF",
    lightPathEnabled: false,
    lightPathColor: "#FFFFFF",
  },
  {
    id: "golden-hour-sun",
    name: "Golden Hour",
    description: "Low warm sun near the horizon with golden glow and light path on water",
    tags: ["sun", "golden", "warm", "sunset"],
    category: "celestial",
    bodyType: "sun",
    elevation: 0.15,
    azimuth: 0.3,
    size: 0.06,
    glowRadius: 0.25,
    glowColor: "#FFD080",
    bodyColor: "#FFE0A0",
    lightPathEnabled: true,
    lightPathColor: "#FFD080",
  },
  {
    id: "harvest-moon",
    name: "Harvest Moon",
    description: "Large warm-toned full moon low on the horizon",
    tags: ["moon", "harvest", "warm", "night"],
    category: "celestial",
    bodyType: "moon",
    elevation: 0.2,
    azimuth: 0.6,
    size: 0.07,
    glowRadius: 0.12,
    glowColor: "#FFE8C0",
    bodyColor: "#FFF0D0",
    lightPathEnabled: true,
    lightPathColor: "#FFE8C0",
  },
  {
    id: "crescent-moon",
    name: "Crescent Moon",
    description: "Thin crescent moon high in a dark sky with cool blue glow",
    tags: ["moon", "crescent", "night", "cool"],
    category: "celestial",
    bodyType: "moon",
    elevation: 0.7,
    azimuth: 0.7,
    size: 0.035,
    moonPhase: 0.15,
    glowRadius: 0.08,
    glowColor: "#C0D8FF",
    bodyColor: "#E8F0FF",
    lightPathEnabled: false,
    lightPathColor: "#C0D8FF",
  },
  {
    id: "blood-moon",
    name: "Blood Moon",
    description: "Deep red-orange moon during lunar eclipse with crimson glow",
    tags: ["moon", "blood", "eclipse", "red"],
    category: "celestial",
    bodyType: "moon",
    elevation: 0.4,
    azimuth: 0.5,
    size: 0.06,
    glowRadius: 0.18,
    glowColor: "#CC4020",
    bodyColor: "#E06040",
    lightPathEnabled: true,
    lightPathColor: "#CC4020",
  },
  {
    id: "polar-star",
    name: "Polar Star",
    description: "Bright point star high in the sky with subtle cross-shaped glow",
    tags: ["star", "bright", "night", "polar"],
    category: "celestial",
    bodyType: "star",
    elevation: 0.9,
    azimuth: 0.5,
    size: 0.015,
    glowRadius: 0.06,
    glowColor: "#E0E8FF",
    bodyColor: "#FFFFFF",
    lightPathEnabled: false,
    lightPathColor: "#E0E8FF",
  },
];
