import type { CliffFacePreset } from "./types.js";

export const CLIFF_FACE_PRESETS: CliffFacePreset[] = [
  {
    id: "granite-cliff",
    name: "Granite Cliff",
    description: "Hard grey granite cliff face with speckled texture and sharp ledges",
    tags: ["granite", "grey", "hard", "mountain"],
    category: "cliff-face",
    textureMode: "granite",
    color: "#808080",
    shadowColor: "#404040",
    height: 0.6,
    xPosition: 0.0,
    width: 0.3,
    roughness: 0.6,
    ledgeCount: 4,
  },
  {
    id: "sandstone-wall",
    name: "Sandstone Wall",
    description: "Warm layered sandstone wall with horizontal strata and erosion patterns",
    tags: ["sandstone", "warm", "layered", "desert"],
    category: "cliff-face",
    textureMode: "sandstone",
    color: "#C4A070",
    shadowColor: "#8A6A40",
    height: 0.5,
    xPosition: 0.0,
    width: 0.35,
    roughness: 0.4,
    ledgeCount: 5,
  },
  {
    id: "basalt-columns",
    name: "Basalt Columns",
    description: "Dark volcanic basalt with vertical columnar jointing",
    tags: ["basalt", "volcanic", "dark", "columns"],
    category: "cliff-face",
    textureMode: "basalt",
    color: "#3A3A40",
    shadowColor: "#1A1A20",
    height: 0.7,
    xPosition: 0.0,
    width: 0.25,
    roughness: 0.3,
    ledgeCount: 2,
  },
  {
    id: "limestone-face",
    name: "Limestone Face",
    description: "Light grey limestone cliff with irregular crack patterns and weathered surface",
    tags: ["limestone", "light", "weathered", "cracks"],
    category: "cliff-face",
    textureMode: "limestone",
    color: "#C0C0B0",
    shadowColor: "#808070",
    height: 0.55,
    xPosition: 0.0,
    width: 0.3,
    roughness: 0.5,
    ledgeCount: 3,
  },
  {
    id: "shale-cliff",
    name: "Shale Cliff",
    description: "Crumbling dark shale cliff with thin horizontal layers and rough edges",
    tags: ["shale", "dark", "crumbling", "layered"],
    category: "cliff-face",
    textureMode: "sandstone",
    color: "#5A5A60",
    shadowColor: "#2A2A30",
    height: 0.5,
    xPosition: 0.0,
    width: 0.28,
    roughness: 0.8,
    ledgeCount: 6,
  },
];
