import type { CloudPreset } from "./types.js";

export const CLOUD_PRESETS: CloudPreset[] = [
  {
    id: "fair-weather",
    name: "Fair Weather",
    category: "clouds",
    description: "Scattered cumulus clouds on a clear day",
    tags: ["cumulus", "light", "clear", "scattered"],
    coverage: 0.3,
    altitudeMin: 0.1,
    altitudeMax: 0.4,
    cloudType: "cumulus",
    scale: 4.0,
    windDirection: 0,
    cloudColor: "#FFFFFF",
    shadowColor: "#A0A8B0",
    softness: 0.5,
  },
  {
    id: "overcast",
    name: "Overcast",
    category: "clouds",
    description: "Heavy stratus cloud cover blanketing the sky",
    tags: ["stratus", "heavy", "grey", "uniform"],
    coverage: 0.75,
    altitudeMin: 0.15,
    altitudeMax: 0.55,
    cloudType: "stratus",
    scale: 3.0,
    windDirection: 0,
    cloudColor: "#D0D0D0",
    shadowColor: "#808890",
    softness: 0.7,
  },
  {
    id: "wispy-high",
    name: "Wispy High",
    category: "clouds",
    description: "Thin cirrus wisps high in the atmosphere",
    tags: ["cirrus", "thin", "high", "wispy"],
    coverage: 0.2,
    altitudeMin: 0.05,
    altitudeMax: 0.25,
    cloudType: "cirrus",
    scale: 6.0,
    windDirection: 15,
    cloudColor: "#F0F0FF",
    shadowColor: "#C0C8D0",
    softness: 0.8,
  },
  {
    id: "storm-clouds",
    name: "Storm Clouds",
    category: "clouds",
    description: "Dense, dark cumulonimbus clouds building before a storm",
    tags: ["cumulus", "dark", "storm", "dramatic"],
    coverage: 0.6,
    altitudeMin: 0.1,
    altitudeMax: 0.5,
    cloudType: "cumulus",
    scale: 3.5,
    windDirection: -10,
    cloudColor: "#B0B0B0",
    shadowColor: "#505860",
    softness: 0.3,
  },
  {
    id: "scattered",
    name: "Scattered",
    category: "clouds",
    description: "Mixed scattered clouds at varying altitudes",
    tags: ["cumulus", "scattered", "mixed", "varied"],
    coverage: 0.4,
    altitudeMin: 0.1,
    altitudeMax: 0.45,
    cloudType: "cumulus",
    scale: 5.0,
    windDirection: 5,
    cloudColor: "#F8F8FF",
    shadowColor: "#9098A0",
    softness: 0.6,
  },
];
