import type { ErosionPreset } from "./types.js";

export const EROSION_PRESETS: ErosionPreset[] = [
  {
    id: "rain-streaks",
    name: "Rain Streaks",
    description: "Vertical rain wash streaks on rock or wall surfaces",
    tags: ["rain", "streaks", "vertical", "wash"],
    category: "erosion",
    erosionType: "rain-wash",
    color: "rgba(60,50,40,0.3)",
    intensity: 0.6,
    coverageTop: 0.25,
    coverageBottom: 0.85,
    noiseScale: 0.5,
  },
  {
    id: "wind-erosion",
    name: "Wind Erosion",
    description: "Horizontal wind scour marks on exposed surfaces",
    tags: ["wind", "scour", "horizontal", "desert"],
    category: "erosion",
    erosionType: "wind-scour",
    color: "rgba(90,80,60,0.25)",
    intensity: 0.5,
    coverageTop: 0.3,
    coverageBottom: 0.75,
    noiseScale: 0.6,
  },
  {
    id: "frost-cracks",
    name: "Frost Cracks",
    description: "Branching crack network from freeze-thaw weathering",
    tags: ["frost", "cracks", "freeze", "weathering"],
    category: "erosion",
    erosionType: "frost-crack",
    color: "rgba(50,50,50,0.35)",
    intensity: 0.55,
    coverageTop: 0.2,
    coverageBottom: 0.8,
    noiseScale: 0.4,
  },
  {
    id: "lichen-growth",
    name: "Lichen Growth",
    description: "Scattered lichen patches on rock surfaces",
    tags: ["lichen", "moss", "organic", "patches"],
    category: "erosion",
    erosionType: "lichen",
    color: "rgba(120,140,80,0.4)",
    intensity: 0.45,
    coverageTop: 0.3,
    coverageBottom: 0.7,
    noiseScale: 0.5,
  },
];
