import type { FencePreset } from "./types.js";

export const FENCE_PRESETS: FencePreset[] = [
  {
    id: "white-picket",
    name: "White Picket",
    description: "Classic white picket fence with pointed tops",
    tags: ["picket", "white", "classic", "garden"],
    category: "fence",
    fenceStyle: "picket",
    color: "#FFFFFF",
    postColor: "#E0E0E0",
    height: 0.06,
    yPosition: 0.7,
    spacing: 0.03,
    sag: 0,
  },
  {
    id: "stone-wall",
    name: "Stone Wall",
    description: "Low dry-stone wall with visible mortar pattern",
    tags: ["stone", "wall", "rural", "masonry"],
    category: "fence",
    fenceStyle: "stone-wall",
    color: "#8A8070",
    postColor: "#6A6050",
    height: 0.05,
    yPosition: 0.72,
    spacing: 0.04,
    sag: 0,
  },
  {
    id: "ranch-rail",
    name: "Ranch Rail",
    description: "Rustic wooden ranch fence with horizontal rails",
    tags: ["ranch", "rail", "wood", "rustic"],
    category: "fence",
    fenceStyle: "rail",
    color: "#7A5A3A",
    postColor: "#5A3A20",
    height: 0.07,
    yPosition: 0.68,
    spacing: 0.06,
    sag: 0.3,
  },
  {
    id: "wire-fence",
    name: "Wire Fence",
    description: "Simple wire fence with wooden posts and sagging wires",
    tags: ["wire", "farm", "simple", "rural"],
    category: "fence",
    fenceStyle: "wire",
    color: "#707070",
    postColor: "#5A4A3A",
    height: 0.08,
    yPosition: 0.65,
    spacing: 0.05,
    sag: 0.5,
  },
];
