import type { FieldPreset } from "./types.js";

export const FIELD_PRESETS: FieldPreset[] = [
  {
    id: "meadow-grass",
    name: "Meadow Grass",
    description: "Soft green meadow with gentle grass marks receding into distance",
    tags: ["grass", "green", "pastoral", "gentle"],
    category: "field",
    vegetationType: "grass",
    color: "#5A8A3A",
    secondaryColor: "#7AAA5A",
    density: 0.6,
    markLength: 8,
    windDirection: 45,
    windStrength: 0.3,
    seasonalTint: "summer",
  },
  {
    id: "wheat-field",
    name: "Wheat Field",
    description: "Golden wheat stalks swaying in perspective rows toward the horizon",
    tags: ["wheat", "golden", "agricultural", "warm"],
    category: "field",
    vegetationType: "wheat",
    color: "#C4A035",
    secondaryColor: "#D4B855",
    density: 0.8,
    markLength: 12,
    windDirection: 90,
    windStrength: 0.5,
    seasonalTint: "autumn",
  },
  {
    id: "wildflower-meadow",
    name: "Wildflower Meadow",
    description: "Colorful wildflower field with scattered blooms among green grass",
    tags: ["flowers", "colorful", "meadow", "spring"],
    category: "field",
    vegetationType: "wildflowers",
    color: "#4A7A3A",
    secondaryColor: "#D45A8A",
    density: 0.5,
    markLength: 6,
    windDirection: 30,
    windStrength: 0.2,
    seasonalTint: "spring",
  },
  {
    id: "lavender-rows",
    name: "Lavender Rows",
    description: "Purple lavender in structured perspective rows with earthy gaps",
    tags: ["lavender", "purple", "rows", "structured"],
    category: "field",
    vegetationType: "wildflowers",
    color: "#7A5AA0",
    secondaryColor: "#9A7AC0",
    density: 0.7,
    markLength: 10,
    windDirection: 0,
    windStrength: 0.1,
    seasonalTint: "summer",
  },
  {
    id: "dry-savanna",
    name: "Dry Savanna",
    description: "Sparse dry grass tufts on warm earth with scattered bare patches",
    tags: ["dry", "savanna", "sparse", "warm"],
    category: "field",
    vegetationType: "grass",
    color: "#B8A060",
    secondaryColor: "#D0C080",
    density: 0.3,
    markLength: 14,
    windDirection: 60,
    windStrength: 0.4,
    seasonalTint: "autumn",
  },
  {
    id: "rice-paddy",
    name: "Rice Paddy",
    description: "Flooded rice paddy with bright green shoots in shallow water rows",
    tags: ["rice", "paddy", "water", "asian"],
    category: "field",
    vegetationType: "grass",
    color: "#6AAA4A",
    secondaryColor: "#8ACC6A",
    density: 0.9,
    markLength: 6,
    windDirection: 0,
    windStrength: 0.1,
    seasonalTint: "summer",
  },
  {
    id: "autumn-stubble",
    name: "Autumn Stubble",
    description: "Harvested field with short stubble and scattered straw remnants",
    tags: ["autumn", "harvested", "stubble", "brown"],
    category: "field",
    vegetationType: "wheat",
    color: "#9A8050",
    secondaryColor: "#B0A070",
    density: 0.4,
    markLength: 4,
    windDirection: 90,
    windStrength: 0.1,
    seasonalTint: "autumn",
  },
  {
    id: "snow-covered",
    name: "Snow-Covered Field",
    description: "White snow blanket with sparse brown grass tips poking through",
    tags: ["snow", "winter", "white", "cold"],
    category: "field",
    vegetationType: "grass",
    color: "#E8E8F0",
    secondaryColor: "#8A7A5A",
    density: 0.2,
    markLength: 5,
    windDirection: 0,
    windStrength: 0.0,
    seasonalTint: "winter",
  },
];
