import type { FogPreset } from "./types.js";

export const FOG_PRESETS: FogPreset[] = [
  {
    id: "morning-mist",
    name: "Morning Mist",
    description: "Soft translucent ground-level mist that partially obscures lower elements",
    tags: ["mist", "morning", "soft", "ground"],
    category: "fog",
    fogType: "ground",
    opacity: 0.4,
    height: 0.2,
    yPosition: 0.7,
    color: "#FFFFFF",
    edgeSoftness: 0.8,
    wispDensity: 0.3,
  },
  {
    id: "mountain-veil",
    name: "Mountain Veil",
    description: "Horizontal fog veil across mid-height mountains, classic shan-shui three-distances effect",
    tags: ["mountain", "veil", "shan-shui", "atmospheric"],
    category: "fog",
    fogType: "mountain",
    opacity: 0.6,
    height: 0.15,
    yPosition: 0.45,
    color: "#F0F0F8",
    edgeSoftness: 0.9,
    wispDensity: 0.5,
  },
  {
    id: "valley-fog",
    name: "Valley Fog",
    description: "Dense fog filling a valley between terrain features, heavier at the base",
    tags: ["valley", "dense", "heavy", "low"],
    category: "fog",
    fogType: "band",
    opacity: 0.7,
    height: 0.25,
    yPosition: 0.6,
    color: "#E8E8F0",
    edgeSoftness: 0.6,
    wispDensity: 0.2,
  },
  {
    id: "shan-shui-cloud-band",
    name: "Shan-Shui Cloud Band",
    description: "Traditional Chinese ink painting cloud band that separates distant and near mountains",
    tags: ["shan-shui", "ink", "cloud-band", "traditional"],
    category: "fog",
    fogType: "band",
    opacity: 0.8,
    height: 0.1,
    yPosition: 0.4,
    color: "#FFFFFF",
    edgeSoftness: 0.95,
    wispDensity: 0.7,
  },
  {
    id: "coastal-haar",
    name: "Coastal Haar",
    description: "Cold sea fog rolling inland, dense and grey with ragged wispy edges",
    tags: ["coastal", "sea-fog", "cold", "grey"],
    category: "fog",
    fogType: "veil",
    opacity: 0.5,
    height: 0.3,
    yPosition: 0.55,
    color: "#D0D0D8",
    edgeSoftness: 0.5,
    wispDensity: 0.6,
  },
];
