import type { ForestFloorPreset } from "./types.js";

export const FOREST_FLOOR_PRESETS: ForestFloorPreset[] = [
  {
    id: "fern-carpet",
    name: "Fern Carpet",
    description: "Dense fern undergrowth covering the forest floor with overlapping fronds",
    tags: ["fern", "green", "dense", "undergrowth"],
    category: "forest-floor",
    coverType: "ferns",
    color: "#3A5A30",
    secondaryColor: "#5A7A40",
    groundColor: "#4A3A28",
    density: 0.7,
    coverageTop: 0.7,
    coverageBottom: 1.0,
  },
  {
    id: "mossy-ground",
    name: "Mossy Ground",
    description: "Soft moss carpet with varied green patches covering rocks and soil",
    tags: ["moss", "soft", "green", "damp"],
    category: "forest-floor",
    coverType: "moss",
    color: "#4A7040",
    secondaryColor: "#608050",
    groundColor: "#3A3020",
    density: 0.8,
    coverageTop: 0.65,
    coverageBottom: 1.0,
  },
  {
    id: "fallen-leaves",
    name: "Fallen Leaves",
    description: "Autumn leaf litter with fallen logs and scattered ground cover",
    tags: ["autumn", "leaves", "logs", "decay"],
    category: "forest-floor",
    coverType: "fallen-logs",
    color: "#8A6030",
    secondaryColor: "#A07040",
    groundColor: "#3A3020",
    density: 0.5,
    coverageTop: 0.7,
    coverageBottom: 1.0,
  },
  {
    id: "pine-needles",
    name: "Pine Needles",
    description: "Conifer forest floor covered in brown pine needles with scattered moss",
    tags: ["pine", "needles", "conifer", "brown"],
    category: "forest-floor",
    coverType: "moss",
    color: "#506030",
    secondaryColor: "#706840",
    groundColor: "#5A4030",
    density: 0.5,
    coverageTop: 0.7,
    coverageBottom: 1.0,
  },
  {
    id: "mushroom-patch",
    name: "Mushroom Patch",
    description: "Forest floor dotted with mushrooms and toadstools among dark soil",
    tags: ["mushroom", "toadstool", "dark", "damp"],
    category: "forest-floor",
    coverType: "mushrooms",
    color: "#C0A080",
    secondaryColor: "#B04030",
    groundColor: "#2A2018",
    density: 0.6,
    coverageTop: 0.75,
    coverageBottom: 1.0,
  },
];
