import type { HazePreset } from "./types.js";

export const HAZE_PRESETS: HazePreset[] = [
  {
    id: "light-haze",
    name: "Light Haze",
    description: "Subtle atmospheric haze that softens distant elements without obscuring them",
    tags: ["light", "subtle", "atmospheric", "soft"],
    category: "haze",
    color: "#E0E8F0",
    opacity: 0.2,
    yPosition: 0.5,
    height: 0.4,
    gradientDirection: "bottom-up",
    noiseAmount: 0.3,
  },
  {
    id: "golden-haze",
    name: "Golden Haze",
    description: "Warm golden atmospheric haze for sunrise or late afternoon scenes",
    tags: ["golden", "warm", "sunrise", "afternoon"],
    category: "haze",
    color: "#F0D8B0",
    opacity: 0.25,
    yPosition: 0.55,
    height: 0.5,
    gradientDirection: "bottom-up",
    noiseAmount: 0.2,
  },
  {
    id: "cool-mist",
    name: "Cool Mist",
    description: "Cool blue-grey mist that adds depth separation between planes",
    tags: ["cool", "blue", "mist", "depth"],
    category: "haze",
    color: "#C0D0E0",
    opacity: 0.3,
    yPosition: 0.6,
    height: 0.35,
    gradientDirection: "center-out",
    noiseAmount: 0.4,
  },
  {
    id: "heat-haze",
    name: "Heat Haze",
    description: "Shimmering heat distortion haze rising from warm ground",
    tags: ["heat", "shimmer", "hot", "desert"],
    category: "haze",
    color: "#F0E8D8",
    opacity: 0.15,
    yPosition: 0.7,
    height: 0.3,
    gradientDirection: "bottom-up",
    noiseAmount: 0.6,
  },
];
