import type { PathPreset } from "./types.js";

export const PATH_PRESETS: PathPreset[] = [
  {
    id: "dirt-trail",
    name: "Dirt Trail",
    category: "path",
    description: "Worn dirt trail through natural terrain",
    tags: ["dirt", "trail", "natural", "worn"],
    pathPreset: "winding",
    widthNear: 120,
    widthFar: 6,
    surfaceColor: "#8B7355",
    surfaceStyle: "dirt",
    edgeTreatment: "grass-encroach",
    wear: 0.5,
  },
  {
    id: "cobblestone-road",
    name: "Cobblestone Road",
    category: "path",
    description: "Old cobblestone road with regular stone pattern",
    tags: ["cobblestone", "road", "stone", "old"],
    pathPreset: "straight",
    widthNear: 200,
    widthFar: 12,
    surfaceColor: "#7A7068",
    surfaceStyle: "cobblestone",
    edgeTreatment: "sharp",
    wear: 0.3,
  },
  {
    id: "gravel-path",
    name: "Gravel Path",
    category: "path",
    description: "Crunchy gravel path through a park or garden",
    tags: ["gravel", "path", "park", "garden"],
    pathPreset: "meandering",
    widthNear: 140,
    widthFar: 8,
    surfaceColor: "#9A9080",
    surfaceStyle: "gravel",
    edgeTreatment: "scattered-stones",
    wear: 0.4,
  },
  {
    id: "forest-path",
    name: "Forest Path",
    category: "path",
    description: "Shaded path through dense forest with encroaching vegetation",
    tags: ["forest", "shaded", "overgrown", "natural"],
    pathPreset: "winding",
    widthNear: 100,
    widthFar: 5,
    surfaceColor: "#6A5A40",
    surfaceStyle: "dirt",
    edgeTreatment: "overgrown",
    wear: 0.7,
  },
  {
    id: "mountain-switchback",
    name: "Mountain Switchback",
    category: "path",
    description: "Steep mountain trail with sharp turns",
    tags: ["mountain", "switchback", "steep", "trail"],
    pathPreset: "switchback",
    widthNear: 90,
    widthFar: 5,
    surfaceColor: "#7A6A55",
    surfaceStyle: "gravel",
    edgeTreatment: "scattered-stones",
    wear: 0.6,
  },
  {
    id: "garden-walk",
    name: "Garden Walk",
    category: "path",
    description: "Elegant flagstone walkway through a formal garden",
    tags: ["garden", "flagstone", "formal", "elegant"],
    pathPreset: "meandering",
    widthNear: 160,
    widthFar: 10,
    surfaceColor: "#8A8070",
    surfaceStyle: "flagstone",
    edgeTreatment: "sharp",
    wear: 0.15,
  },
  {
    id: "sand-track",
    name: "Sand Track",
    category: "path",
    description: "Sandy track through dunes or along the coast",
    tags: ["sand", "track", "dunes", "coastal"],
    pathPreset: "meandering",
    widthNear: 130,
    widthFar: 8,
    surfaceColor: "#C4A870",
    surfaceStyle: "sand",
    edgeTreatment: "grass-encroach",
    wear: 0.3,
  },
  {
    id: "country-lane",
    name: "Country Lane",
    category: "path",
    description: "Quiet country lane with grass growing through worn ruts",
    tags: ["country", "lane", "quiet", "rural"],
    pathPreset: "straight",
    widthNear: 180,
    widthFar: 12,
    surfaceColor: "#7A7050",
    surfaceStyle: "worn-grass",
    edgeTreatment: "grass-encroach",
    wear: 0.6,
  },
];
