import type { ProfilePreset } from "./types.js";

export const PROFILE_PRESETS: ProfilePreset[] = [
  {
    id: "alpine-range",
    name: "Alpine Range",
    category: "profile",
    description: "Sharp, jagged alpine peaks with multiple receding ridges",
    tags: ["mountains", "alpine", "jagged", "dramatic"],
    ridgeCount: 5,
    roughness: 0.8,
    elevationMin: 0.2,
    elevationMax: 0.6,
    noiseScale: 3.0,
    jaggedness: 0.7,
    foregroundColor: "#2D3B2D",
    backgroundRidgeColor: "#8BA4B8",
    depthValueShift: 0.6,
    depthEasing: "quadratic",
  },
  {
    id: "rolling-hills",
    name: "Rolling Hills",
    category: "profile",
    description: "Gentle, smooth rolling hills with soft contours",
    tags: ["hills", "gentle", "pastoral", "soft"],
    ridgeCount: 3,
    roughness: 0.2,
    elevationMin: 0.5,
    elevationMax: 0.75,
    noiseScale: 1.5,
    jaggedness: 0.1,
    foregroundColor: "#3B5E3B",
    backgroundRidgeColor: "#7A9E8A",
    depthValueShift: 0.4,
    depthEasing: "linear",
  },
  {
    id: "mesa-plateau",
    name: "Mesa Plateau",
    category: "profile",
    description: "Flat-topped mesa formations with steep cliff sides",
    tags: ["desert", "mesa", "flat-top", "arid"],
    ridgeCount: 2,
    roughness: 0.4,
    elevationMin: 0.35,
    elevationMax: 0.55,
    noiseScale: 2.0,
    jaggedness: 0.9,
    foregroundColor: "#8B5E3C",
    backgroundRidgeColor: "#C4A882",
    depthValueShift: 0.3,
    depthEasing: "linear",
  },
  {
    id: "coastal-cliffs",
    name: "Coastal Cliffs",
    category: "profile",
    description: "Dramatic coastal cliffs with weathered profiles",
    tags: ["coast", "cliffs", "dramatic", "ocean"],
    ridgeCount: 2,
    roughness: 0.6,
    elevationMin: 0.4,
    elevationMax: 0.65,
    noiseScale: 2.5,
    jaggedness: 0.5,
    foregroundColor: "#4A4A3A",
    backgroundRidgeColor: "#8A9AA0",
    depthValueShift: 0.35,
    depthEasing: "quadratic",
  },
  {
    id: "sand-dunes",
    name: "Sand Dunes",
    category: "profile",
    description: "Smooth undulating sand dunes with minimal roughness",
    tags: ["desert", "dunes", "smooth", "sand"],
    ridgeCount: 4,
    roughness: 0.15,
    elevationMin: 0.55,
    elevationMax: 0.8,
    noiseScale: 1.2,
    jaggedness: 0.05,
    foregroundColor: "#C4A55A",
    backgroundRidgeColor: "#E8D5A0",
    depthValueShift: 0.25,
    depthEasing: "linear",
  },
  {
    id: "foothills",
    name: "Foothills",
    category: "profile",
    description: "Low foothills transitioning from plains with moderate elevation",
    tags: ["hills", "foothills", "transitional", "moderate"],
    ridgeCount: 4,
    roughness: 0.35,
    elevationMin: 0.5,
    elevationMax: 0.7,
    noiseScale: 2.0,
    jaggedness: 0.25,
    foregroundColor: "#3A5030",
    backgroundRidgeColor: "#7090A0",
    depthValueShift: 0.45,
    depthEasing: "quadratic",
  },
];
