import type { ProfilePreset } from "./types.js";

export const PROFILE_PRESETS: ProfilePreset[] = [
  {
    id: "alpine-range",
    name: "Alpine Range",
    category: "profile",
    description: "Sharp, jagged alpine peaks with multiple receding ridges",
    tags: ["mountains", "alpine", "jagged", "dramatic"],
    ridgeCount: 7,
    roughness: 0.8,
    elevationMin: 0.30,
    elevationMax: 0.85,
    noiseScale: 3.0,
    jaggedness: 0.7,
    foregroundColor: "#1A2E1A",
    backgroundRidgeColor: "#8BAABE",
    depthValueShift: 0.7,
    depthEasing: "quadratic",
  },
  {
    id: "rolling-hills",
    name: "Rolling Hills",
    category: "profile",
    description: "Gentle, smooth rolling hills with soft contours",
    tags: ["hills", "gentle", "pastoral", "soft"],
    ridgeCount: 5,
    roughness: 0.2,
    elevationMin: 0.45,
    elevationMax: 0.80,
    noiseScale: 1.5,
    jaggedness: 0.1,
    foregroundColor: "#2A4A2A",
    backgroundRidgeColor: "#90B0A0",
    depthValueShift: 0.5,
    depthEasing: "linear",
  },
  {
    id: "mesa-plateau",
    name: "Mesa Plateau",
    category: "profile",
    description: "Flat-topped mesa formations with steep cliff sides",
    tags: ["desert", "mesa", "flat-top", "arid"],
    ridgeCount: 4,
    roughness: 0.4,
    elevationMin: 0.35,
    elevationMax: 0.70,
    noiseScale: 2.0,
    jaggedness: 0.9,
    foregroundColor: "#6B3E1C",
    backgroundRidgeColor: "#D4B892",
    depthValueShift: 0.45,
    depthEasing: "linear",
  },
  {
    id: "coastal-cliffs",
    name: "Coastal Cliffs",
    category: "profile",
    description: "Dramatic coastal cliffs with weathered profiles",
    tags: ["coast", "cliffs", "dramatic", "ocean"],
    ridgeCount: 4,
    roughness: 0.6,
    elevationMin: 0.35,
    elevationMax: 0.75,
    noiseScale: 2.5,
    jaggedness: 0.5,
    foregroundColor: "#3A3A2A",
    backgroundRidgeColor: "#9AAAB0",
    depthValueShift: 0.5,
    depthEasing: "quadratic",
  },
  {
    id: "sand-dunes",
    name: "Sand Dunes",
    category: "profile",
    description: "Smooth undulating sand dunes with minimal roughness",
    tags: ["desert", "dunes", "smooth", "sand"],
    ridgeCount: 6,
    roughness: 0.15,
    elevationMin: 0.50,
    elevationMax: 0.85,
    noiseScale: 1.2,
    jaggedness: 0.05,
    foregroundColor: "#B4953A",
    backgroundRidgeColor: "#E8D5A0",
    depthValueShift: 0.35,
    depthEasing: "linear",
  },
  {
    id: "foothills",
    name: "Foothills",
    category: "profile",
    description: "Low foothills transitioning from plains with moderate elevation",
    tags: ["hills", "foothills", "transitional", "moderate"],
    ridgeCount: 5,
    roughness: 0.35,
    elevationMin: 0.45,
    elevationMax: 0.80,
    noiseScale: 2.0,
    jaggedness: 0.25,
    foregroundColor: "#2A4020",
    backgroundRidgeColor: "#80A0B0",
    depthValueShift: 0.55,
    depthEasing: "quadratic",
  },
];
