import type { ReflectionPreset } from "./types.js";

export const REFLECTION_PRESETS: ReflectionPreset[] = [
  {
    id: "calm-lake",
    name: "Calm Lake",
    description: "Near-perfect mirror reflection on still lake water with minimal ripple",
    tags: ["calm", "lake", "mirror", "still"],
    category: "reflection",
    skyColor: "#87CEEB",
    terrainColor: "#3A5A30",
    darkening: 0.25,
    rippleFrequency: 0.2,
    rippleAmplitude: 0.1,
    waterlinePosition: 0.5,
    blurAmount: 0.2,
  },
  {
    id: "rippled-reflection",
    name: "Rippled Reflection",
    description: "Broken reflection on water with moderate ripple distortion",
    tags: ["rippled", "broken", "water", "wind"],
    category: "reflection",
    skyColor: "#6AAEDC",
    terrainColor: "#2A4A28",
    darkening: 0.35,
    rippleFrequency: 0.7,
    rippleAmplitude: 0.5,
    waterlinePosition: 0.5,
    blurAmount: 0.5,
  },
  {
    id: "dark-water",
    name: "Dark Water",
    description: "Deep dark water reflection with strong darkening and subtle movement",
    tags: ["dark", "deep", "moody", "dramatic"],
    category: "reflection",
    skyColor: "#4A6A8A",
    terrainColor: "#1A2A18",
    darkening: 0.5,
    rippleFrequency: 0.3,
    rippleAmplitude: 0.2,
    waterlinePosition: 0.5,
    blurAmount: 0.6,
  },
  {
    id: "golden-reflection",
    name: "Golden Reflection",
    description: "Warm golden hour reflection with amber-tinted sky and terrain colors",
    tags: ["golden", "warm", "sunset", "amber"],
    category: "reflection",
    skyColor: "#E8A040",
    terrainColor: "#4A3A20",
    darkening: 0.2,
    rippleFrequency: 0.4,
    rippleAmplitude: 0.3,
    waterlinePosition: 0.5,
    blurAmount: 0.3,
  },
];
