import type { RiverPreset } from "./types.js";

export const RIVER_PRESETS: RiverPreset[] = [
  {
    id: "gentle-stream",
    name: "Gentle Stream",
    category: "river",
    description: "Narrow, calm stream winding through a meadow",
    tags: ["stream", "calm", "narrow", "meadow"],
    pathPreset: "meandering",
    widthNear: 140,
    widthFar: 8,
    waterColor: "#4A7A8A",
    bankColor: "#5C6B3A",
    rippleScale: 0.3,
    rippleIntensity: 0.2,
    reflectionIntensity: 0.3,
    flowDirection: 1,
    bankStyle: "soft-grass",
  },
  {
    id: "wide-river",
    name: "Wide River",
    category: "river",
    description: "Broad, powerful river flowing through a valley",
    tags: ["river", "wide", "powerful", "valley"],
    pathPreset: "meandering",
    widthNear: 320,
    widthFar: 25,
    waterColor: "#2A5060",
    bankColor: "#6B5A3A",
    rippleScale: 0.6,
    rippleIntensity: 0.5,
    reflectionIntensity: 0.4,
    flowDirection: 1,
    bankStyle: "muddy",
  },
  {
    id: "mountain-creek",
    name: "Mountain Creek",
    category: "river",
    description: "Fast rocky creek tumbling down a mountainside",
    tags: ["creek", "mountain", "rocky", "fast"],
    pathPreset: "switchback",
    widthNear: 100,
    widthFar: 5,
    waterColor: "#5A8A9A",
    bankColor: "#7A7A6A",
    rippleScale: 0.8,
    rippleIntensity: 0.7,
    reflectionIntensity: 0.15,
    flowDirection: 1,
    bankStyle: "rocky",
  },
  {
    id: "lazy-oxbow",
    name: "Lazy Oxbow",
    category: "river",
    description: "Slow, winding oxbow curve in flat terrain",
    tags: ["oxbow", "lazy", "winding", "flat"],
    pathPreset: "s-curve",
    widthNear: 220,
    widthFar: 18,
    waterColor: "#3A6070",
    bankColor: "#5A5030",
    rippleScale: 0.15,
    rippleIntensity: 0.1,
    reflectionIntensity: 0.6,
    flowDirection: 1,
    bankStyle: "muddy",
  },
  {
    id: "forest-brook",
    name: "Forest Brook",
    category: "river",
    description: "Shaded brook under a forest canopy",
    tags: ["brook", "forest", "shaded", "peaceful"],
    pathPreset: "winding",
    widthNear: 90,
    widthFar: 4,
    waterColor: "#3A5A50",
    bankColor: "#4A5A30",
    rippleScale: 0.4,
    rippleIntensity: 0.3,
    reflectionIntensity: 0.2,
    flowDirection: 1,
    bankStyle: "soft-grass",
  },
  {
    id: "delta-channels",
    name: "Delta Channels",
    category: "river",
    description: "Branching river delta with multiple channels",
    tags: ["delta", "branches", "channels", "flat"],
    pathPreset: "fork",
    widthNear: 180,
    widthFar: 15,
    waterColor: "#4A6A70",
    bankColor: "#6A6A50",
    rippleScale: 0.2,
    rippleIntensity: 0.15,
    reflectionIntensity: 0.35,
    flowDirection: 1,
    bankStyle: "sandy",
  },
  {
    id: "waterfall-stream",
    name: "Waterfall Stream",
    category: "river",
    description: "Steep stream with cascading water and white rapids",
    tags: ["waterfall", "steep", "rapids", "white"],
    pathPreset: "straight",
    widthNear: 120,
    widthFar: 6,
    waterColor: "#5A9AAA",
    bankColor: "#6A6A5A",
    rippleScale: 1.0,
    rippleIntensity: 0.9,
    reflectionIntensity: 0.05,
    flowDirection: 1,
    bankStyle: "rocky",
  },
  {
    id: "tidal-estuary",
    name: "Tidal Estuary",
    category: "river",
    description: "Wide estuary where river meets the sea",
    tags: ["estuary", "tidal", "wide", "coastal"],
    pathPreset: "straight",
    widthNear: 400,
    widthFar: 35,
    waterColor: "#3A5A6A",
    bankColor: "#7A7060",
    rippleScale: 0.5,
    rippleIntensity: 0.4,
    reflectionIntensity: 0.45,
    flowDirection: 1,
    bankStyle: "sandy",
  },
];
