import type { RockPreset } from "./types.js";

export const ROCK_PRESETS: RockPreset[] = [
  {
    id: "granite-boulder",
    name: "Granite Boulder",
    description: "Large rounded granite boulder with speckled grey texture",
    tags: ["granite", "boulder", "grey", "rounded"],
    category: "rock",
    rockType: "boulder",
    textureMode: "speckled",
    color: "#8A8A8A",
    shadowColor: "#4A4A4A",
    scale: 1.0,
    roughness: 0.5,
    crackDensity: 0.3,
  },
  {
    id: "sandstone-outcrop",
    name: "Sandstone Outcrop",
    description: "Layered sandstone outcrop with warm horizontal striations",
    tags: ["sandstone", "layered", "warm", "striated"],
    category: "rock",
    rockType: "outcrop",
    textureMode: "striated",
    color: "#C4A070",
    shadowColor: "#8A6A40",
    scale: 1.2,
    roughness: 0.4,
    crackDensity: 0.5,
  },
  {
    id: "shan-shui-rock",
    name: "Shan-Shui Rock",
    description: "Traditional Chinese landscape rock with cun-fa texture strokes",
    tags: ["shan-shui", "chinese", "cun-fa", "ink", "traditional"],
    category: "rock",
    rockType: "pinnacle",
    textureMode: "cun-fa",
    color: "#3A3A3A",
    shadowColor: "#1A1A1A",
    scale: 1.5,
    roughness: 0.8,
    crackDensity: 0.7,
  },
  {
    id: "mossy-rock",
    name: "Mossy Rock",
    description: "Weathered rock with patches of green moss on its surface",
    tags: ["moss", "green", "weathered", "organic"],
    category: "rock",
    rockType: "boulder",
    textureMode: "speckled",
    color: "#6A7A6A",
    shadowColor: "#3A4A3A",
    scale: 0.8,
    roughness: 0.6,
    crackDensity: 0.2,
  },
  {
    id: "slate-shelf",
    name: "Slate Shelf",
    description: "Flat angular slate shelf with sharp edges and dark blue-grey tones",
    tags: ["slate", "flat", "angular", "dark"],
    category: "rock",
    rockType: "shelf",
    textureMode: "striated",
    color: "#5A6070",
    shadowColor: "#2A3040",
    scale: 0.6,
    roughness: 0.3,
    crackDensity: 0.6,
  },
  {
    id: "volcanic-basalt",
    name: "Volcanic Basalt",
    description: "Dark columnar basalt with hexagonal cracking patterns",
    tags: ["volcanic", "basalt", "dark", "columnar"],
    category: "rock",
    rockType: "outcrop",
    textureMode: "cracked",
    color: "#2A2A30",
    shadowColor: "#101015",
    scale: 1.0,
    roughness: 0.7,
    crackDensity: 0.9,
  },
];
