import type { ShorePreset } from "./types.js";

export const SHORE_PRESETS: ShorePreset[] = [
  {
    id: "sandy-beach",
    name: "Sandy Beach",
    category: "shore",
    description: "Wide sandy beach with gentle foam line",
    tags: ["sandy", "beach", "foam", "gentle"],
    shoreType: "sandy-beach",
    width: 0.08,
    color: "#D4C4A0",
    wetColor: "#B0A080",
    foamLine: true,
    foamIntensity: 0.5,
    debrisType: "shells",
  },
  {
    id: "rocky-shore",
    name: "Rocky Shore",
    category: "shore",
    description: "Rugged rocky shoreline with crashing surf",
    tags: ["rocky", "rugged", "surf", "dramatic"],
    shoreType: "rocky-shore",
    width: 0.06,
    color: "#6A6A5A",
    wetColor: "#4A4A3A",
    foamLine: true,
    foamIntensity: 0.8,
    debrisType: "seaweed",
  },
  {
    id: "muddy-riverbank",
    name: "Muddy Riverbank",
    category: "shore",
    description: "Soft muddy bank along a river",
    tags: ["muddy", "riverbank", "soft", "wet"],
    shoreType: "muddy-bank",
    width: 0.05,
    color: "#6A5A3A",
    wetColor: "#4A3A20",
    foamLine: false,
    foamIntensity: 0,
    debrisType: "none",
  },
  {
    id: "grassy-bank",
    name: "Grassy Bank",
    category: "shore",
    description: "Gentle grassy slope meeting the water",
    tags: ["grassy", "bank", "gentle", "green"],
    shoreType: "grassy-bank",
    width: 0.07,
    color: "#5A7A3A",
    wetColor: "#4A6030",
    foamLine: false,
    foamIntensity: 0,
    debrisType: "none",
  },
  {
    id: "tidal-flat",
    name: "Tidal Flat",
    category: "shore",
    description: "Exposed tidal flat with wet sand and pools",
    tags: ["tidal", "flat", "wet", "pools"],
    shoreType: "tidal-flat",
    width: 0.1,
    color: "#B0A080",
    wetColor: "#8A8068",
    foamLine: true,
    foamIntensity: 0.3,
    debrisType: "seaweed",
  },
  {
    id: "cliff-base",
    name: "Cliff Base",
    category: "shore",
    description: "Narrow strip at the base of sea cliffs",
    tags: ["cliff", "base", "narrow", "dramatic"],
    shoreType: "cliff-base",
    width: 0.03,
    color: "#5A5A4A",
    wetColor: "#3A3A2A",
    foamLine: true,
    foamIntensity: 0.9,
    debrisType: "pebbles",
  },
];
