import type { SkyPreset } from "./types.js";

export const SKY_PRESETS: SkyPreset[] = [
  {
    id: "dawn",
    name: "Dawn",
    category: "sky",
    description: "Early morning sky with warm pink-orange horizon fading to pale blue zenith",
    tags: ["warm", "morning", "sunrise", "soft"],
    zenithColor: "#4A6FA5",
    horizonColor: "#F4A460",
    hazeColor: "#FFB6C1",
    hazeIntensity: 0.4,
    hazePosition: 0.85,
    hazeWidth: 0.15,
  },
  {
    id: "noon",
    name: "Noon",
    category: "sky",
    description: "Clear midday sky with deep blue zenith and pale blue horizon",
    tags: ["bright", "clear", "midday", "blue"],
    zenithColor: "#1E3A6E",
    horizonColor: "#87CEEB",
    hazeColor: "#B0D4E8",
    hazeIntensity: 0.15,
    hazePosition: 0.9,
    hazeWidth: 0.1,
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    category: "sky",
    description: "Late afternoon golden light with amber horizon and warm blue zenith",
    tags: ["warm", "golden", "afternoon", "atmospheric"],
    zenithColor: "#2C5F8A",
    horizonColor: "#E8A317",
    hazeColor: "#F0C75E",
    hazeIntensity: 0.5,
    hazePosition: 0.8,
    hazeWidth: 0.2,
  },
  {
    id: "dusk",
    name: "Dusk",
    category: "sky",
    description: "Twilight sky with deep purple zenith and burnt orange horizon",
    tags: ["cool", "evening", "twilight", "purple"],
    zenithColor: "#1A0A2E",
    horizonColor: "#D4622A",
    hazeColor: "#8B4D6E",
    hazeIntensity: 0.35,
    hazePosition: 0.75,
    hazeWidth: 0.2,
  },
  {
    id: "night",
    name: "Night",
    category: "sky",
    description: "Dark night sky with near-black zenith and deep navy horizon",
    tags: ["dark", "night", "cool", "moody"],
    zenithColor: "#050510",
    horizonColor: "#0E1A2B",
    hazeColor: "#1A2540",
    hazeIntensity: 0.1,
    hazePosition: 0.9,
    hazeWidth: 0.1,
  },
];
