import type { SnowfieldPreset } from "./types.js";

export const SNOWFIELD_PRESETS: SnowfieldPreset[] = [
  {
    id: "fresh-powder",
    name: "Fresh Powder",
    description: "Freshly fallen snow with soft drift patterns and bright sparkle",
    tags: ["fresh", "powder", "soft", "bright"],
    category: "snowfield",
    snowColor: "#F0F4F8",
    shadowColor: "#B0C0D8",
    driftIntensity: 0.4,
    sparkleIntensity: 0.5,
    coverageTop: 0.5,
    coverageBottom: 1.0,
  },
  {
    id: "wind-swept",
    name: "Wind Swept",
    description: "Wind-sculpted snow with pronounced drift ridges and blue-grey shadows",
    tags: ["wind", "swept", "ridges", "cold"],
    category: "snowfield",
    snowColor: "#E8ECF0",
    shadowColor: "#8898B0",
    driftIntensity: 0.8,
    sparkleIntensity: 0.2,
    coverageTop: 0.4,
    coverageBottom: 1.0,
  },
  {
    id: "sun-crust",
    name: "Sun Crust",
    description: "Sun-warmed snow crust with golden-tinted highlights and high sparkle",
    tags: ["sun", "crust", "warm", "sparkle"],
    category: "snowfield",
    snowColor: "#F8F0E8",
    shadowColor: "#C0B0A0",
    driftIntensity: 0.3,
    sparkleIntensity: 0.8,
    coverageTop: 0.5,
    coverageBottom: 1.0,
  },
  {
    id: "deep-snow",
    name: "Deep Snow",
    description: "Deep accumulated snow with blue-tinted shadows in hollows",
    tags: ["deep", "blue", "accumulated", "winter"],
    category: "snowfield",
    snowColor: "#F0F0FA",
    shadowColor: "#90A0C0",
    driftIntensity: 0.6,
    sparkleIntensity: 0.15,
    coverageTop: 0.3,
    coverageBottom: 1.0,
  },
];
