import type { StarfieldPreset } from "./types.js";

export const STARFIELD_PRESETS: StarfieldPreset[] = [
  {
    id: "clear-night",
    name: "Clear Night",
    description: "Clear dark sky with moderate star density and natural color variation",
    tags: ["night", "clear", "stars", "default"],
    category: "starfield",
    starCount: 200,
    brightnessRange: 0.7,
    maxSize: 3.0,
    starColor: "#FFFFFF",
    warmTint: 0.1,
    milkyWayEnabled: false,
    milkyWayAngle: 30,
    milkyWayIntensity: 0.15,
    constellationHints: false,
  },
  {
    id: "dense-starfield",
    name: "Dense Starfield",
    description: "Rich star-packed sky for deep rural or high-altitude scenes",
    tags: ["dense", "rural", "many", "bright"],
    category: "starfield",
    starCount: 600,
    brightnessRange: 0.9,
    maxSize: 3.5,
    starColor: "#FFFFFF",
    warmTint: 0.15,
    milkyWayEnabled: false,
    milkyWayAngle: 30,
    milkyWayIntensity: 0.15,
    constellationHints: false,
  },
  {
    id: "milky-way",
    name: "Milky Way",
    description: "Night sky with visible Milky Way band and dense star field",
    tags: ["milky-way", "galaxy", "band", "dense"],
    category: "starfield",
    starCount: 500,
    brightnessRange: 0.8,
    maxSize: 3.0,
    starColor: "#F8F0E8",
    warmTint: 0.2,
    milkyWayEnabled: true,
    milkyWayAngle: 30,
    milkyWayIntensity: 0.15,
    constellationHints: false,
  },
  {
    id: "sparse-stars",
    name: "Sparse Stars",
    description: "Few bright stars for light-polluted or early twilight scenes",
    tags: ["sparse", "few", "urban", "subtle"],
    category: "starfield",
    starCount: 40,
    brightnessRange: 0.5,
    maxSize: 2.5,
    starColor: "#FFFFFF",
    warmTint: 0.05,
    milkyWayEnabled: false,
    milkyWayAngle: 30,
    milkyWayIntensity: 0.15,
    constellationHints: false,
  },
  {
    id: "twilight-stars",
    name: "Twilight Stars",
    description: "Early evening stars appearing during blue hour with warm tints",
    tags: ["twilight", "evening", "warm", "blue-hour"],
    category: "starfield",
    starCount: 80,
    brightnessRange: 0.4,
    maxSize: 2.0,
    starColor: "#E8E0D0",
    warmTint: 0.3,
    milkyWayEnabled: false,
    milkyWayAngle: 30,
    milkyWayIntensity: 0.15,
    constellationHints: true,
  },
];
