import type { TreelinePreset } from "./types.js";

export const TREELINE_PRESETS: TreelinePreset[] = [
  {
    id: "deciduous-canopy",
    name: "Deciduous Canopy",
    description: "Dense rounded deciduous tree canopy band with lush green foliage",
    tags: ["deciduous", "green", "rounded", "lush"],
    category: "treeline",
    canopyStyle: "rounded",
    color: "#3A6A2A",
    highlightColor: "#5A8A4A",
    shadowColor: "#1A4A10",
    density: 0.8,
    height: 0.15,
    irregularity: 0.4,
  },
  {
    id: "conifer-ridge",
    name: "Conifer Ridge",
    description: "Pointed conifer silhouettes along a mountain ridgeline",
    tags: ["conifer", "pine", "pointed", "mountain"],
    category: "treeline",
    canopyStyle: "pointed",
    color: "#2A4A2A",
    highlightColor: "#3A6A3A",
    shadowColor: "#0A2A0A",
    density: 0.9,
    height: 0.2,
    irregularity: 0.6,
  },
  {
    id: "autumn-treeline",
    name: "Autumn Treeline",
    description: "Mixed autumn foliage band with warm oranges, reds, and yellows",
    tags: ["autumn", "fall", "warm", "colorful"],
    category: "treeline",
    canopyStyle: "rounded",
    color: "#C47030",
    highlightColor: "#D4A040",
    shadowColor: "#8A4020",
    density: 0.7,
    height: 0.15,
    irregularity: 0.5,
  },
  {
    id: "misty-forest",
    name: "Misty Forest",
    description: "Soft forest band partially obscured by atmospheric haze",
    tags: ["misty", "hazy", "atmospheric", "soft"],
    category: "treeline",
    canopyStyle: "rounded",
    color: "#5A7A6A",
    highlightColor: "#7A9A8A",
    shadowColor: "#3A5A4A",
    density: 0.6,
    height: 0.12,
    irregularity: 0.3,
  },
  {
    id: "palm-fringe",
    name: "Palm Fringe",
    description: "Tropical palm tree silhouettes with fan-shaped fronds",
    tags: ["palm", "tropical", "silhouette", "warm"],
    category: "treeline",
    canopyStyle: "fan",
    color: "#2A5A2A",
    highlightColor: "#4A7A4A",
    shadowColor: "#0A3A0A",
    density: 0.5,
    height: 0.18,
    irregularity: 0.7,
  },
  {
    id: "winter-bare",
    name: "Winter Bare",
    description: "Bare winter tree silhouettes with exposed branch structure",
    tags: ["winter", "bare", "branches", "sparse"],
    category: "treeline",
    canopyStyle: "bare",
    color: "#4A3A30",
    highlightColor: "#6A5A50",
    shadowColor: "#2A1A10",
    density: 0.4,
    height: 0.16,
    irregularity: 0.6,
  },
];
