import type { VignetteFoliagePreset } from "./types.js";

export const VIGNETTE_FOLIAGE_PRESETS: VignetteFoliagePreset[] = [
  {
    id: "overhanging-branches",
    name: "Overhanging Branches",
    description: "Tree branches hanging into the frame from above with leaf clusters",
    tags: ["branches", "tree", "top", "framing"],
    category: "vignette-foliage",
    foliageStyle: "branches",
    color: "#2A4A20",
    secondaryColor: "#4A6A30",
    density: 0.5,
    depth: 0.15,
    edges: "top",
  },
  {
    id: "grass-border",
    name: "Grass Border",
    description: "Tall grass blades framing the bottom edge of the scene",
    tags: ["grass", "bottom", "tall", "border"],
    category: "vignette-foliage",
    foliageStyle: "grass-blades",
    color: "#3A5A28",
    secondaryColor: "#5A7A38",
    density: 0.7,
    depth: 0.12,
    edges: "bottom",
  },
  {
    id: "leaf-frame",
    name: "Leaf Frame",
    description: "Scattered leaves framing all edges for a canopy peek effect",
    tags: ["leaves", "frame", "canopy", "all-sides"],
    category: "vignette-foliage",
    foliageStyle: "leaves",
    color: "#2A5020",
    secondaryColor: "#408030",
    density: 0.6,
    depth: 0.18,
    edges: "all",
  },
  {
    id: "pine-canopy",
    name: "Pine Canopy",
    description: "Dark pine branches framing the top and sides of the scene",
    tags: ["pine", "conifer", "dark", "canopy"],
    category: "vignette-foliage",
    foliageStyle: "branches",
    color: "#1A3A18",
    secondaryColor: "#2A4A20",
    density: 0.4,
    depth: 0.2,
    edges: "top-sides",
  },
  {
    id: "vine-border",
    name: "Vine Border",
    description: "Trailing vines with small leaves creeping in from the edges",
    tags: ["vine", "trailing", "creeping", "organic"],
    category: "vignette-foliage",
    foliageStyle: "vines",
    color: "#305828",
    secondaryColor: "#4A7838",
    density: 0.5,
    depth: 0.15,
    edges: "top-sides",
  },
];
