import type { WaterPreset } from "./types.js";

export const WATER_PRESETS: WaterPreset[] = [
  {
    id: "still-lake",
    name: "Still Lake",
    category: "water",
    description: "Calm, mirror-like lake surface with minimal ripples",
    tags: ["calm", "lake", "mirror", "peaceful"],
    waterlinePosition: 0.6,
    rippleFrequency: 8,
    rippleAmplitude: 0.5,
    rippleMode: "sine",
    waterColor: "#2A4A6B",
    depthDarkening: 0.4,
    shimmerIntensity: 0.15,
  },
  {
    id: "choppy-sea",
    name: "Choppy Sea",
    category: "water",
    description: "Rough ocean surface with strong waves and whitecaps",
    tags: ["ocean", "rough", "waves", "dramatic"],
    waterlinePosition: 0.55,
    rippleFrequency: 25,
    rippleAmplitude: 3.0,
    rippleMode: "noise",
    waterColor: "#1A3A5C",
    depthDarkening: 0.6,
    shimmerIntensity: 0.3,
  },
  {
    id: "mountain-stream",
    name: "Mountain Stream",
    category: "water",
    description: "Clear mountain stream with visible ripple patterns",
    tags: ["stream", "clear", "mountain", "fresh"],
    waterlinePosition: 0.75,
    rippleFrequency: 15,
    rippleAmplitude: 1.5,
    rippleMode: "noise",
    waterColor: "#3A6A7A",
    depthDarkening: 0.25,
    shimmerIntensity: 0.4,
  },
  {
    id: "river",
    name: "River",
    category: "water",
    description: "Wide river with moderate current and surface texture",
    tags: ["river", "moderate", "flowing", "wide"],
    waterlinePosition: 0.65,
    rippleFrequency: 12,
    rippleAmplitude: 1.0,
    rippleMode: "sine",
    waterColor: "#2E5060",
    depthDarkening: 0.45,
    shimmerIntensity: 0.2,
  },
  {
    id: "pond",
    name: "Pond",
    category: "water",
    description: "Small quiet pond with subtle surface movement",
    tags: ["pond", "quiet", "small", "still"],
    waterlinePosition: 0.7,
    rippleFrequency: 6,
    rippleAmplitude: 0.3,
    rippleMode: "sine",
    waterColor: "#2A4050",
    depthDarkening: 0.5,
    shimmerIntensity: 0.1,
  },
];
